name: Black linter + isort

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@master
        with:
            sortPaths: "./01_advanced_basics"
      - uses: psf/black@stable
        with:
            options: "--check --verbose"
            src: "./01_advanced_basics"
            version: "~= 22.0"