name: Tests

on: [push, pull_request]

jobs:
  run_tests_01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: python test_log_analyzer.py
        working-directory: ./01_advanced_basics
  run_tests_03:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: python test_log_analyzer.py
        working-directory: ./03_oop