name: Tests

on: [push, pull_request]

jobs:
  run_tests_01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: python test_log_analyzer.py
        working-directory: ./01_advanced_basics
  run_tests_03:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: python test.py
        working-directory: ./03_oop
  run_tests_04:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install redis fakeredis
      - name: Run Tests
        run: python -m unittest
        working-directory: ./04_testing